[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ['npm install --workspaces']

[phases.build]
cmds = [
  'npm run build:shared',
  'npm run build:backend',
  'npm run build:frontend'
]

[start]
cmd = 'npm start --workspace=backend'
